var vocabularies = [
	{
		"name": "0-100", 
		"description": "Japanese numbers 0-20, and 10's up to 100", 
		"source": "Genki 1", 
		"data": [
			{"kana": "ゼロ", "romaji": "zero", "english": ["zero", "0"]},
			{"kana": "いち", "romaji": "ichi", "english": ["one", "1"]},
			{"kana": "に", "romaji": "ni", "english": ["two", "2"]},
			{"kana": "さん", "romaji": "san", "english": ["three", "3"]},
			{"kana": "よん", "romaji": "yon", "english": ["four", "4"]},
			{"kana": "し", "romaji": "shi", "english": ["four", "4"]},
			{"kana": "よ", "romaji": "yo", "english": ["four", "4"]},
			{"kana": "ご", "romaji": "go", "english": ["five", "5"]},
			{"kana": "ろく", "romaji": "roku", "english": ["six", "6"]},
			{"kana": "なな", "romaji": "nana", "english": ["seven", "7"]},
			{"kana": "しち", "romaji": "shichi", "english": ["seven", "7"]},
			{"kana": "はち", "romaji": "hachi", "english": ["eight", "8"]},
			{"kana": "きゅう", "romaji": "kyuu", "english": ["nine", "9"]},
			{"kana": "く", "romaji": "ku", "english": ["nine", "9"]},
			{"kana": "じゅう", "romaji": "juu", "english": ["ten", "10"]},
			{"kana": "じゅういち", "romaji": "juuichi", "english": ["eleven", "11"]},
			{"kana": "じゅうに", "romaji": "juuni", "english": ["twelve", "12"]},
			{"kana": "じゅうさん", "romaji": "juusan", "english": ["thirteen", "13"]},
			{"kana": "じゅうよん", "romaji": "juuyon", "english": ["fourteen", "14"]},
			{"kana": "じゅうし", "romaji": "juushi", "english": ["fourteen", "14"]},
			{"kana": "じゅうご", "romaji": "juugo", "english": ["fifteen", "15"]},
			{"kana": "じゅうろく", "romaji": "juuroku", "english": ["sixteen", "16"]},
			{"kana": "じゅうなな", "romaji": "juunana", "english": ["seventeen", "17"]},
			{"kana": "じゅうしち", "romaji": "juushichi", "english": ["seventeen", "17"]},
			{"kana": "じゅうはち", "romaji": "juuhachi", "english": ["eighteen", "18"]},
			{"kana": "じゅうきゅう", "romaji": "juukyuu", "english": ["nineteen", "19"]},
			{"kana": "じゅうく", "romaji": "juuku", "english": ["nineteen", "19"]},
			{"kana": "にじゅう", "romaji": "nijuu", "english": ["twenty", "20"]},
			{"kana": "さんじゅう", "romaji": "sanjuu", "english": ["thirty", "30"]},
			{"kana": "よんじゅう", "romaji": "yonjuu", "english": ["fourty", "40"]},
			{"kana": "ごじゅう", "romaji": "gojuu", "english": ["fifty", "50"]},
			{"kana": "ろくじゅう", "romaji": "rokujuu", "english": ["sixty", "60"]},
			{"kana": "ななじゅう", "romaji": "nanajuu", "english": ["seventy", "70"]},
			{"kana": "はちじゅう", "romaji": "hachijuu", "english": ["eighty", "80"]},
			{"kana": "きゅうじゅう", "romaji": "kyuujuu", "english": ["ninety", "90"]},
			{"kana": "ひゃく", "romaji": "hyaku", "english": ["one hundred", "100", "hundred"]},
		]
	},
	{
		"name": "Greetings",
		"description": "Various greetings",
		"source": "Genki 1",
		"data": [
			{"kana": "おはよう", "romaji": "ohayoo", "english": {"english": "good morning", "description": "casual"}},
			{"kana": "おはようございます", "romaji": "ohayoo gozaimasu", "english": {"english": "good morning", "description": "polite"}},
			{"kana": "こんいちは", "romaji": "konnichiwa", "english": "good afternoon"},
			{"kana": "こんばんは", "romaji": "konbanwa", "english": "good evening"},
			{"kana": "さようなら", "romaji": "sayoonara", "english": "goodbye"},
			{"kana": "おやすみなさい", "romaji": "oyasuminasai", "english": "good night"},
			{"kana": "ありがとう", "romaji": "arigatoo", "english": {"english": "thank you", "description": "casual"}},
			{"kana": "ありがとうございます", "romaji": "arigatoo gozaimasu", "english": {"english": "thank you", "description": "polite"}},
			{"kana": "すみません", "romaji": "sumimasen", "english": ["excuse me", "i'm sorry"]},
			{"kana": "いいえ", "romaji": "iie", "english": ["no", "not at all"]},
			{"kana": "いってきます", "romaji": "ittekimasu", "english": "i'l go and come back"},
			{"kana": "いってらっしゃい", "romaji": "itterasshai", "english": "please go and come back"},
			{"kana": "ただいま", "romaji": "tadaima", "english": "i'm home"},
			{"kana": "おかえりなさい", "romaji": "okaerinasai", "english": "welcome home"},
			{"kana": "いただきます", "romaji": "itadakimasu", "english": {"english": "thank you for the meal", "description": "before"}},
			{"kana": "ごちそうさま", "romaji": "gochisoosama", "english": {"english": "thank you for the meal", "description": "after"}},
			{"kana": "はじめまして", "romaji": "hajimemashite", "english": "how do you do"},
			{"kana": "どうぞよろしく", "romaji": "doozo yoroshiku", "english": "nice to meet you"},
		]
	}
];